/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceArtifactsArtifactIdRouteImport } from './routes/_workspace.artifacts.$artifactId'
import { Route as WorkspaceChatsIndexRouteImport } from './routes/_workspace.chats.index'
import { Route as WorkspaceChatsChatIdRouteImport } from './routes/_workspace.chats.$chatId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceArtifactsArtifactIdRoute =
  WorkspaceArtifactsArtifactIdRouteImport.update({
    id: '/artifacts/$artifactId',
    path: '/artifacts/$artifactId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceChatsIndexRoute = WorkspaceChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceChatsChatIdRoute = WorkspaceChatsChatIdRouteImport.update({
  id: '/chats/$chatId',
  path: '/chats/$chatId',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts/$artifactId': typeof WorkspaceArtifactsArtifactIdRoute
  '/chats/$chatId': typeof WorkspaceChatsChatIdRoute
  '/chats/': typeof WorkspaceChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts/$artifactId': typeof WorkspaceArtifactsArtifactIdRoute
  '/chats/$chatId': typeof WorkspaceChatsChatIdRoute
  '/chats': typeof WorkspaceChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/artifacts/$artifactId': typeof WorkspaceArtifactsArtifactIdRoute
  '/_workspace/chats/$chatId': typeof WorkspaceChatsChatIdRoute
  '/_workspace/chats/': typeof WorkspaceChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/artifacts/$artifactId' | '/chats/$chatId' | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/artifacts/$artifactId' | '/chats/$chatId' | '/chats'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/_workspace/artifacts/$artifactId'
    | '/_workspace/chats/$chatId'
    | '/_workspace/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/artifacts/$artifactId': {
      id: '/_workspace/artifacts/$artifactId'
      path: '/artifacts/$artifactId'
      fullPath: '/artifacts/$artifactId'
      preLoaderRoute: typeof WorkspaceArtifactsArtifactIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/chats/': {
      id: '/_workspace/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof WorkspaceChatsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/chats/$chatId': {
      id: '/_workspace/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof WorkspaceChatsChatIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceArtifactsArtifactIdRoute: typeof WorkspaceArtifactsArtifactIdRoute
  WorkspaceChatsChatIdRoute: typeof WorkspaceChatsChatIdRoute
  WorkspaceChatsIndexRoute: typeof WorkspaceChatsIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceArtifactsArtifactIdRoute: WorkspaceArtifactsArtifactIdRoute,
  WorkspaceChatsChatIdRoute: WorkspaceChatsChatIdRoute,
  WorkspaceChatsIndexRoute: WorkspaceChatsIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
