// Generated from the deterministic fixture shapes by scripts/generate.mjs.
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  customers: defineTable({
    fixture: v.string(),
    customerRef: v.string(),
    name: v.string(),
    email: v.string(),
    country: v.string(),
    city: v.string(),
    acquisitionChannel: v.string(),
    createdAt: v.number(),
    loyaltyTier: v.string(),
  }).index("by_ref", ["customerRef"]),
  products: defineTable({
    fixture: v.string(),
    sku: v.string(),
    name: v.string(),
    category: v.string(),
    priceCents: v.number(),
    costCents: v.number(),
    supplier: v.string(),
    leadTimeDays: v.number(),
  }).index("by_sku", ["sku"]),
  orders: defineTable({
    fixture: v.string(),
    orderRef: v.string(),
    customerRef: v.string(),
    createdAt: v.number(),
    date: v.string(),
    status: v.string(),
    channel: v.string(),
    campaign: v.string(),
    device: v.string(),
    browser: v.string(),
    country: v.string(),
    warehouse: v.string(),
    currency: v.string(),
    grossCents: v.number(),
    discountCents: v.number(),
    netCents: v.number(),
    taxCents: v.number(),
    shippingChargedCents: v.number(),
    totalCents: v.number(),
    cogsCents: v.number(),
    shippingCostCents: v.number(),
    paymentFeeCents: v.number(),
    isFirstOrder: v.boolean(),
  })
    .index("by_ref", ["orderRef"])
    .index("by_created", ["createdAt"])
    .index("by_customer", ["customerRef", "createdAt"]),
  orderItems: defineTable({
    fixture: v.string(),
    itemRef: v.string(),
    orderRef: v.string(),
    customerRef: v.string(),
    sku: v.string(),
    category: v.string(),
    quantity: v.number(),
    unitPriceCents: v.number(),
    grossCents: v.number(),
    discountCents: v.number(),
    netCents: v.number(),
    costCents: v.number(),
    batch: v.string(),
    createdAt: v.number(),
  })
    .index("by_order", ["orderRef"])
    .index("by_sku", ["sku", "createdAt"]),
  paymentAttempts: defineTable({
    fixture: v.string(),
    paymentRef: v.string(),
    orderRef: v.string(),
    createdAt: v.number(),
    attempt: v.number(),
    provider: v.string(),
    method: v.string(),
    status: v.string(),
    errorCode: v.union(v.null(), v.string()),
    amountCents: v.number(),
    latencyMs: v.number(),
    browser: v.string(),
    device: v.string(),
    release: v.string(),
  })
    .index("by_order", ["orderRef"])
    .index("by_created", ["createdAt"]),
  shipments: defineTable({
    fixture: v.string(),
    shipmentRef: v.string(),
    orderRef: v.string(),
    customerRef: v.string(),
    createdAt: v.number(),
    date: v.string(),
    warehouse: v.string(),
    carrier: v.string(),
    country: v.string(),
    shippedAt: v.union(v.number(), v.null()),
    deliveredAt: v.union(v.number(), v.null()),
    promisedAt: v.number(),
    status: v.string(),
    delayReason: v.union(v.null(), v.string()),
    costCents: v.number(),
  })
    .index("by_order", ["orderRef"])
    .index("by_status", ["status", "createdAt"]),
  returns: defineTable({
    fixture: v.string(),
    returnRef: v.string(),
    orderRef: v.string(),
    customerRef: v.string(),
    sku: v.string(),
    quantity: v.number(),
    batch: v.string(),
    requestedAt: v.number(),
    refundedAt: v.union(v.number(), v.null()),
    status: v.string(),
    reason: v.string(),
    refundCents: v.number(),
    requestedRefundCents: v.number(),
  }).index("by_sku", ["sku", "requestedAt"]),
  supportTickets: defineTable({
    fixture: v.string(),
    ticketRef: v.string(),
    orderRef: v.string(),
    customerRef: v.string(),
    createdAt: v.number(),
    category: v.string(),
    priority: v.string(),
    status: v.string(),
    firstResponseMinutes: v.number(),
    resolvedAt: v.union(v.number(), v.null()),
    csat: v.union(v.number(), v.null()),
    subject: v.string(),
  }).index("by_status", ["status", "createdAt"]),
  inventory: defineTable({
    fixture: v.string(),
    sku: v.string(),
    warehouse: v.string(),
    onHand: v.number(),
    reserved: v.number(),
    reorderPoint: v.number(),
    inboundUnits: v.number(),
    expectedArrival: v.union(v.number(), v.null()),
    leadTimeDays: v.number(),
    updatedAt: v.number(),
  }).index("by_sku", ["sku"]),
  marketingSpend: defineTable({
    fixture: v.string(),
    date: v.string(),
    channel: v.string(),
    campaign: v.string(),
    spendCents: v.number(),
    impressions: v.number(),
    clicks: v.number(),
  }).index("by_date", ["date"]),
  dailyRevenue: defineTable({
    fixture: v.string(),
    date: v.string(),
    orders: v.number(),
    paidOrders: v.number(),
    failedOrders: v.number(),
    grossSalesCents: v.number(),
    discountCents: v.number(),
    netSalesCents: v.number(),
    cogsCents: v.number(),
    shippingCostCents: v.number(),
    paymentFeesCents: v.number(),
    refundCents: v.number(),
    adSpendCents: v.number(),
    contributionCents: v.number(),
  }).index("by_date", ["date"]),
  channelDaily: defineTable({
    fixture: v.string(),
    date: v.string(),
    channel: v.string(),
    orders: v.number(),
    paidOrders: v.number(),
    newCustomers: v.number(),
    netSalesCents: v.number(),
    cogsCents: v.number(),
    shippingCostCents: v.number(),
    paymentFeesCents: v.number(),
    refundCents: v.number(),
    adSpendCents: v.number(),
    contributionCents: v.number(),
  }).index("by_date", ["date"]),
  checkoutDaily: defineTable({
    fixture: v.string(),
    date: v.string(),
    browser: v.string(),
    device: v.string(),
    attempts: v.number(),
    failed: v.number(),
    callbackTimeouts: v.number(),
    latencyTotalMs: v.number(),
  }).index("by_date", ["date"]),
  fulfillmentDaily: defineTable({
    fixture: v.string(),
    date: v.string(),
    warehouse: v.string(),
    carrier: v.string(),
    orders: v.number(),
    delivered: v.number(),
    deliveredLate: v.number(),
    overdueOpen: v.number(),
    unfulfilled: v.number(),
    totalDeliveryDays: v.number(),
  }).index("by_date", ["date"]),
  productDaily: defineTable({
    fixture: v.string(),
    date: v.string(),
    sku: v.string(),
    category: v.string(),
    units: v.number(),
    netSalesCents: v.number(),
    cogsCents: v.number(),
    refundCents: v.number(),
  }).index("by_sku", ["sku", "date"]),
  retentionCohorts: defineTable({
    fixture: v.string(),
    cohort: v.string(),
    ageWeek: v.number(),
    activeCustomers: v.number(),
    orders: v.number(),
    netSalesCents: v.number(),
    cohortCustomers: v.number(),
  }).index("by_cohort", ["cohort", "ageWeek"]),
  deployments: defineTable({
    fixture: v.string(),
    release: v.string(),
    deployedAt: v.number(),
    service: v.string(),
    description: v.string(),
  }).index("by_time", ["deployedAt"]),
  serviceMetrics: defineTable({
    fixture: v.string(),
    timestamp: v.number(),
    service: v.string(),
    requests: v.number(),
    errors: v.number(),
    p50Ms: v.number(),
    p95Ms: v.number(),
    queueDepth: v.number(),
    release: v.string(),
  }).index("by_service", ["service", "timestamp"]),
  datasetInfo: defineTable({
    fixture: v.string(),
    key: v.string(),
    valueJson: v.string(),
  }).index("by_key", ["key"]),
});
